### ISSUE TITLE
enumerator fails if kfd path does not exist

### ISSUE THREAD

**Issue by acxz** [ROCm/rocminfo#56]
```
Traceback (most recent call last):
  File "/opt/rocm/bin/rocm_agent_enumerator", line 257, in <module>
    main()
  File "/opt/rocm/bin/rocm_agent_enumerator", line 241, in main
    target_list = readFromKFD()
  File "/opt/rocm/bin/rocm_agent_enumerator", line 193, in readFromKFD
    for node in sorted(os.listdir(topology_dir)):
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/kfd/kfd/topology/nodes/'
```

**Comment by acxz** [comment]
fixed with d8f236c
